version: 2.1
jobs:
 build:
   # docker:
   #   - image: cimg/go:1.13
   machine:
     - image: ubuntu-1604:201903-01
       docker_layer_caching: true
   steps:
     - checkout
     - run: docker build .
