version: 2.1
jobs:
 build:
   # docker:
   #   - image: cimg/go:1.13
   machine: true
   steps:
     - checkout
     - setup_remote_docker:
         docker_layer_caching: true
     - run: docker build .
