version: 2.1
jobs:
  build:
    machine:
      # image: ubuntu-1604:201903-01
      # docker_layer_caching: true
      resource_class: gpu.nvidia.small
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - checkout
      - run: docker build .
