version: 2.1
jobs:
  build:
    # machine:
      # image: ubuntu-1604:201903-01
      # docker_layer_caching: true
    docker:
      - image: cimg/go
    steps:
      - checkout
      - setup_remote_docker:
         docker_layer_caching: true
      - run: docker build .
